{
  "format_version": 2,
  "sksl": {
    "entrypoint": "room_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform float uTime;\nuniform float uTimeline;\nuniform float uEnergy;\nuniform float uLow;\nuniform float uHigh;\nuniform float uBeat;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nfloat FLT_flutter_local_hash(vec2 p)\n{\n    return fract(sin(dot(p, vec2(127.09999847412109375, 311.70001220703125))) * 43758.546875);\n}\n\nvoid FLT_main()\n{\n    vec2 frag = FLT_flutter_local_FlutterFragCoord();\n    vec2 uv = frag / uSize;\n    float aspect = uSize.x / uSize.y;\n    vec2 c = vec2((uv.x - 0.5) * aspect, uv.y - 0.5);\n    vec3 col = vec3(0.01200000010430812835693359375, 0.0130000002682209014892578125, 0.014999999664723873138427734375);\n    col *= (1.0 - (0.300000011920928955078125 * uv.y));\n    float sweepX = 0.5 + (0.300000011920928955078125 * sin((uTime * 0.2199999988079071044921875) + (uTimeline * 2.0)));\n    float beam = exp(-pow((uv.x - sweepX) * 2.599999904632568359375, 2.0));\n    float beamFade = smoothstep(0.0, 0.85000002384185791015625, 1.0 - uv.y);\n    col += ((((vec3(0.300000011920928955078125, 0.305000007152557373046875, 0.310000002384185791015625) * beam) * beamFade) * (0.07999999821186065673828125 + (uEnergy * 0.14000000059604644775390625))) * uTimeline);\n    vec2 param = frag + vec2(uTime * 60.0);\n    float g = FLT_flutter_local_hash(param);\n    col += vec3((g - 0.5) * 0.0199999995529651641845703125);\n    float r = length(c);\n    float vig = smoothstep(1.2000000476837158203125, 0.300000011920928955078125, r);\n    col *= mix(0.550000011920928955078125, 1.0, vig);\n    fragColor = vec4(col, 1.0);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uTimeline",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 3,
        "name": "uEnergy",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 4,
        "name": "uLow",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 5,
        "name": "uHigh",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 6,
        "name": "uBeat",
        "rows": 1,
        "type": 10
      }
    ]
  }
}